/**
 * attune-codelevel.ts — code-level /attune entrypoint (Sprint 2, Task 2.3)
 *
 * grimoires/loa/sprint.md:L146; SDD §1.5 (F1 data flow), §4.3.
 *
 * Ties the F1 pipeline together: analyze(repo) → reconcile(vs game-state) → a cited Markdown
 * DriftReport written under grimoires/gygax/balance-reports/. Invoked by the /attune skill ONLY
 * when a repo is present; the no-repo/tabletop path stays the skill's existing behavior
 * (additive, graceful fallback — prd.md:L101).
 *
 * The renderer carries every structural claim's citation through to the Markdown, and surfaces
 * `silentOn` explicitly so the human sees what was NOT asserted (honesty by visibility).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { analyze, type StructuralMap } from "./static-analyzer.ts";
import { reconcile, type DriftReport } from "./drift-reconciler.ts";

export function renderDriftReportMarkdown(map: StructuralMap, report: DriftReport): string {
  const lines: string[] = [];
  lines.push(`# Drift Report — ${map.repo} @ ${map.commit}`);
  lines.push("");
  lines.push("_Generated by Gygax code-level `/attune`. Every structural claim is cited; uncertain wiring is listed under “Silent On”, never asserted._");
  lines.push("");

  // Numeric drift
  lines.push(`## Numeric Drift (${report.numericDeltas.length})`);
  if (report.numericDeltas.length === 0) {
    lines.push("");
    lines.push("_No numeric disagreements between code and game-state._");
  } else {
    lines.push("");
    lines.push("| Field | Code | game-state | Source | Leads |");
    lines.push("|-------|------|-----------|--------|-------|");
    for (const d of report.numericDeltas) {
      lines.push(`| \`${d.field}\` | ${d.code} | ${d.gameState} | \`${d.source}\` | ${d.leads} |`);
    }
  }
  lines.push("");

  // Structural drift
  lines.push(`## Structural Drift (${report.structuralDeltas.length})`);
  if (report.structuralDeltas.length === 0) {
    lines.push("");
    lines.push("_No structural disagreements on traced wiring._");
  } else {
    lines.push("");
    for (const s of report.structuralDeltas) {
      const where = s.inCode && !s.inGameState ? "in code, not in game-state" : "in game-state, not in code";
      lines.push(`- \`${s.claim}\` — ${where} (\`${s.source}\`) [${s.confidence}]`);
    }
  }
  lines.push("");

  // Tunability (FR-3) — additive: only rendered when ≥1 value carries an inferred tag, so the
  // report is byte-identical for engines with no engine-tuning signal (non-regression).
  const tagged = map.numbers.filter((n) => n.tunability);
  if (tagged.length > 0) {
    lines.push(`## Tunability (inferred, ${tagged.length})`);
    lines.push("");
    lines.push("_`engine-default` reads as “yours to tune — here’s the lever”; `structural` reads as a genuine engine constraint._");
    lines.push("");
    for (const n of tagged) {
      lines.push(`- \`${n.name}\` = ${n.value} → **${n.tunability}** (\`${n.source}\`)`);
    }
    lines.push("");
  }

  // Formulas (FR-3 real-code hardening) — the tuning surface: values defined by a formula, not a
  // literal. Additive: only rendered when present, so the report is byte-identical otherwise.
  const formulas = map.formulas ?? [];
  if (formulas.length > 0) {
    lines.push(`## Tuning Surface — formulas (${formulas.length})`);
    lines.push("");
    lines.push("_Values defined by a formula (a candidate `model:` block for `/augury --sweep`)._");
    lines.push("");
    for (const f of formulas) {
      const tag = f.tunability ? ` [${f.tunability}]` : "";
      lines.push(`- \`${f.name}\` = \`${f.formula.replace(/\s+/g, " ")}\`${tag} (\`${f.source}\`)`);
    }
    lines.push("");
  }

  // Silent on (the honesty section)
  lines.push(`## Silent On (${report.silentOn.length}) — untraceable wiring, NOT asserted`);
  lines.push("");
  if (report.silentOn.length === 0) {
    lines.push("_Nothing untraceable encountered._");
  } else {
    for (const s of report.silentOn) lines.push(`- ${s}`);
  }
  lines.push("");
  return lines.join("\n");
}

export interface AttuneCodeLevelResult {
  reportPath: string;
  map: StructuralMap;
  report: DriftReport;
}

/**
 * Run the full code-level /attune pipeline and write the Markdown report.
 * @param repoPath engine root
 * @param gameStateDir the construct's game-state directory
 * @param outDir destination (defaults to grimoires/gygax/balance-reports/)
 */
export function attuneCodeLevel(
  repoPath: string,
  gameStateDir: string,
  outDir = "grimoires/gygax/balance-reports",
): AttuneCodeLevelResult {
  const map = analyze(repoPath);
  const report = reconcile(map, gameStateDir);
  const md = renderDriftReportMarkdown(map, report);
  mkdirSync(outDir, { recursive: true });
  // Deterministic, collision-resistant filename without Date.now() (unavailable in some envs).
  const reportPath = join(outDir, `drift-${map.repo}-${map.commit}.md`);
  writeFileSync(reportPath, md, "utf8");
  return { reportPath, map, report };
}

// CLI: `npx tsx scripts/lib/codegrounding/attune-codelevel.ts <repoPath> <gameStateDir> [outDir]`
if (process.argv[1]?.endsWith("attune-codelevel.ts")) {
  const [, , repoPath, gameStateDir, outDir] = process.argv;
  if (!repoPath || !gameStateDir) {
    process.stderr.write(
      "usage: attune-codelevel.ts <repoPath> <gameStateDir> [outDir]\n",
    );
    process.exit(2);
  }
  const result = attuneCodeLevel(repoPath, gameStateDir, outDir);
  process.stdout.write(`drift report written: ${result.reportPath}\n`);
  process.stdout.write(
    `numeric=${result.report.numericDeltas.length} structural=${result.report.structuralDeltas.length} silentOn=${result.report.silentOn.length}\n`,
  );
}
