/**
 * report.ts — deterministic Markdown for the parametric sweep (cycle-005, FR-1, B.7).
 *
 * Crossover table + spike list + tunability framing (engine-default → "yours to tune"; structural →
 * "genuine engine constraint" — FR-3 wiring consumed here, K5). No `Date.now()` — stable output,
 * mirroring attune-codelevel.ts's renderer.
 */
import type { MetricSeries } from "./sweep.ts";
import type { Crossover, Spike } from "./crossover.ts";
import type { KnobRanking } from "./sensitivity.ts";

export interface TunabilityTag {
  id: string;
  tunability: "engine-default" | "structural";
}

export interface SweepResult {
  variable: string;
  domain: { min: number; max: number };
  series: MetricSeries[];
  crossovers: Crossover[];
  spikes: Spike[];
  /** All tunability-tagged entities (models AND structural non-model entities), for K5 framing. */
  tags: TunabilityTag[];
  /** Knob-leverage ranking (FR-2); present when sensitivity analysis ran. */
  knobs?: KnobRanking;
}

/** FR-2 inline knob report: ranked tunable knobs + L4 crossover column + L7 escalations. */
export function renderKnobReport(ranking: KnobRanking, primaryMetric: string, variable: string): string {
  const lines: string[] = [];
  lines.push(`## Tuning Knobs — leverage ranking (FR-2)`);
  lines.push("");
  if (ranking.knobs.length === 0) {
    lines.push("_No tunable knobs found._");
  } else {
    lines.push(`| Rank | Knob | Leverage (Σ\\|Δ ${primaryMetric}\\|) | Direction | Crossover-mover (L4) | Note |`);
    lines.push("|-----:|------|----------------------:|-----------|---------------------|------|");
    ranking.knobs.forEach((k, i) => {
      const l4 =
        k.crossoverShift === null
          ? "—"
          : k.crossoverShift === 0
            ? "no shift"
            : `${k.crossoverShift > 0 ? "+" : ""}${k.crossoverShift} on \`${variable}\``;
      lines.push(`| ${i + 1} | \`${k.id}\` | ${k.leverage} | ${k.direction} | ${l4} | ${k.secondaryNote ?? ""} |`);
    });
  }
  lines.push("");
  if (ranking.findings.length > 0) {
    lines.push("**Balance findings — false levers (not knobs):**");
    for (const f of ranking.findings) lines.push(`- ${f.note}`);
    lines.push("");
  }
  if (ranking.excludedStructural.length > 0) {
    lines.push("**Structural invariants — never proposed as knobs:**");
    for (const id of ranking.excludedStructural) lines.push(`- \`${id}\``);
    lines.push("");
  }
  return lines.join("\n");
}

export function renderSweepReport(result: SweepResult): string {
  const lines: string[] = [];
  lines.push(`# Parametric Sweep — variable \`${result.variable}\`, domain ${result.domain.min}–${result.domain.max}`);
  lines.push("");
  lines.push("_Generated by Gygax `/augury --sweep`. Numeric sweep + first-crossing & spike detection — no symbolic solving._");
  lines.push("");

  // Crossover table (K2)
  lines.push(`## Threshold Crossings (${result.crossovers.length})`);
  lines.push("");
  if (result.crossovers.length === 0) {
    lines.push("_No declared thresholds._");
  } else {
    lines.push("| Metric | Threshold | First crossing |");
    lines.push("|--------|-----------|----------------|");
    for (const c of result.crossovers) {
      const where = c.x === null ? "_no crossing in domain_" : `\`${result.variable} = ${c.x}\` (value ${c.at})`;
      lines.push(`| \`${c.metric}\` | ${c.op} ${c.value} | ${where} |`);
    }
  }
  lines.push("");

  // Spike list (K3)
  lines.push(`## Spikes — threshold-free drastic jumps (${result.spikes.length})`);
  lines.push("");
  if (result.spikes.length === 0) {
    lines.push("_No drastic jumps detected (curves trend smoothly)._");
  } else {
    lines.push("| Metric | At | Jump | × local trend |");
    lines.push("|--------|----|------|---------------|");
    for (const s of result.spikes) {
      lines.push(`| \`${s.metric}\` | \`${result.variable} = ${s.x}\` | ${s.jump >= 0 ? "+" : ""}${s.jump} → ${s.value} | ${s.relativeJump.toFixed(1)}× |`);
    }
  }
  lines.push("");

  // Knob report (FR-2) — inline, before the framing summary.
  if (result.knobs) {
    const primary = result.knobs.knobs[0]?.primaryMetric ?? "metric";
    lines.push(renderKnobReport(result.knobs, primary, result.variable));
  }

  // Tunability framing (K5)
  if (result.tags.length > 0) {
    lines.push(`## Tunability Framing (${result.tags.length})`);
    lines.push("");
    const defaults = result.tags.filter((t) => t.tunability === "engine-default");
    const structural = result.tags.filter((t) => t.tunability === "structural");
    if (defaults.length > 0) {
      lines.push("**Engine-default — yours to tune (here are the levers):**");
      for (const t of defaults) lines.push(`- \`${t.id}\``);
      lines.push("");
    }
    if (structural.length > 0) {
      lines.push("**Structural — genuine engine constraints (not knobs):**");
      for (const t of structural) lines.push(`- \`${t.id}\``);
      lines.push("");
    }
  }

  return lines.join("\n");
}
